// import the Gupter font
import { Mukta } from "next/font/google";
import ThemeProviderWrapper from "../themproviderwrapper/ThemeProviderWrapper";
// import Header from "./header/page";

const mukta = Mukta({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mukta.className}>
        {/* <Header /> */}
        <ThemeProviderWrapper>{children}</ThemeProviderWrapper>
      </body>
    </html>
  );
}
