// // src/app/layout.js (Server Component)
// import { ThemeProvider } from "@mui/material/styles";
// import theme from "@/theme/theme"; // Import your theme
// import Footer from "@/components/footer/Footer";
// import Header from "@/components/header/Header";
// import { Global } from "@emotion/react"; // Global styles

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function Layout({ children }) {
//   return (
//     <html lang="en">
//       <head>
//         <link
//           href="https://fonts.googleapis.com/css2?family=Reddit+Sans:wght@400;500;600;700&display=swap"
//           rel="stylesheet"
//         />
//       </head>
//       <body>
//         <Global
//           styles={{
//             "html, body": {
//               margin: 0,
//               padding: 0,
//               height: "100%",
//               width: "100%",
//             },
//             "#__next": {
//               height: "100%",
//             },
//           }}
//         />
//         <Header />
//         <ThemeProvider theme={theme}>{children}</ThemeProvider>
//         <Footer />
//       </body>
//     </html>
//   );
// }

// ............................................................

// import { ThemeProvider } from "@mui/material/styles";
// import theme from "@/theme/theme"; // Adjust the path as necessary
// import Footer from "@/components/footer/Footer";
// import Header from "@/components/header/Header";
// import "./globals.css";
// // Import Quicksand font

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <head>
//         <link
//           href="https://fonts.googleapis.com/css2?family=Reddit+Sans:wght@400;500;600;700&display=swap"
//           rel="stylesheet"
//         />
//       </head>
//       <body className="reddit-font">
//         <ThemeProvider theme={theme}>
//           <Header />
//           {children}
//           <Footer />
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }

// ................................................................

// layout.jsx
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/theme/theme";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import "./globals.css";

// Import font using `next/font`
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Removed 600
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <ThemeProvider theme={theme}>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
